project:
  type: website
  
execute:
  enabled: false

website:
  title: "Bioinformatics self-learning journey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rust/
        text: Rust
      - href: deep-learning-for-life-sciences/
        text: Deep Learning
      - href: git-version-control/
        text: Git version control

format:
  html:
    theme: cosmo
    toc: true
